cfg_scale:
  default: 7.0
  type: float
height:
  default: 512
  type: int
image_path:
  default: ''
  type: string
prompt:
  default: A cute baby sea otter
  type: string
width:
  default: 512
  type: int
